app/consultas/forms.py

from ast import Str
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileAllowed
from wtforms import (StringField, SubmitField, TextAreaField, BooleanField, DateField,  SelectField, HiddenField)
from wtforms.fields import FloatField, IntegerField
from wtforms.validators import DataRequired, Length, Email, NumberRange


class BusquedaForm(FlaskForm):
    buscar = StringField('Buscar')

app/consultas/__init__.py
from flask import Blueprint

consultas_bp = Blueprint('consultas', __name__, template_folder='templates')

from . import routes

app/consultas/routes.py
import logging

from datetime import date, datetime, timedelta

from flask import render_template, redirect, url_for, abort, current_app, flash, request
from flask_login import login_required, current_user

from app.auth.decorators import admin_required, not_initial_status
from app.auth.models import Users
from app.models import Gestiones, Cobros, ImportesCobros, Estados, TiposGestiones, Observaciones, Personas, GestionesDeTareas

from . import consultas_bp 
from .forms import BusquedaForm


logger = logging.getLogger(__name__)

def control_vencimiento (fecha):
    if fecha < datetime.now():
        return "VENCIDO"

@consultas_bp.route("/consultas/consultapersonas/", methods = ['GET', 'POST'])
@login_required
@not_initial_status
def consulta_personas():
    criterio = request.args.get('criterio','')

    form = BusquedaForm()
    lista_de_personas = []
    page = int(request.args.get('page', 1))
    per_page = current_app.config['ITEMS_PER_PAGE']
    if form.validate_on_submit():
        buscar = form.buscar.data
        return redirect(url_for("consultas.consulta_personas", criterio = buscar))
    if criterio.isdigit() == True:
        lista_de_personas = Personas.get_by_cuit(criterio)
    elif criterio == "":
        pass
    else:
        lista_de_personas = Personas.get_like_descripcion_all_paginated(criterio, page, per_page)
        if len(lista_de_personas.items) == 0:
            lista_de_personas =[]

    return render_template("consultas/consulta_personas.html", form = form, criterio = criterio, lista_de_personas= lista_de_personas )

@consultas_bp.route("/consultas/listagestiones/", methods = ['GET', 'POST'])
@login_required
@not_initial_status
def lista_gestiones():
    criterio = request.args.get('criterio','')
    cuit = request.args.get('cuit','')
    form = BusquedaForm()
    
    page = int(request.args.get('page', 1))
    per_page = current_app.config['ITEMS_PER_PAGE']
    gestiones = Gestiones.get_all_paginated(page, per_page)

    if len(gestiones.items) == 0:
            gestiones =[]

    if form.validate_on_submit():
        buscar = form.buscar.data
        return redirect(url_for("consultas.lista_gestiones", criterio = buscar))
    
    if criterio:
        if criterio.isdigit():
            gestiones = Gestiones.get_by_id(criterio)
            return render_template("consultas/lista_gestiones.html", form = form, criterio = criterio, gestiones = gestiones )
        else :
            gestiones = Gestiones.get_like_descripcion_all_paginated(criterio, page, per_page)
            if len(gestiones.items) == 0:
                gestiones =[]
            return render_template("consultas/lista_gestiones_criterio.html", form = form, criterio = criterio, gestiones = gestiones )
    
    if cuit: 
        id_cliente = Personas.get_by_cuit(cuit)
        gestiones = Gestiones.get_gestiones_by_id_cliente_all_paginated(id_cliente.id, page, per_page)
        if len(gestiones.items) == 0:
            gestiones =[]
        return render_template("consultas/lista_gestiones_cuit_her.html", form=form, gestiones=gestiones, cuit=cuit)
    else:
        gestiones = Gestiones.get_like_descripcion_all_paginated(criterio, page, per_page)
        if len(gestiones.items) == 0:
            gestiones =[]
        
        return render_template("consultas/lista_gestiones_all_her.html", form=form, gestiones=gestiones)

@consultas_bp.route("/consultas/cobro/")
@login_required
@admin_required
@not_initial_status
def cobro():
    id_gestion = request.args.get('id_gestion','')
    cobro_individual = Gestiones.get_by_id(id_gestion)
    
    if cobro_individual:
        return render_template("consultas/cobro.html", cobro_individual = cobro_individual)
    flash("La gestión no tiene dado de alta un presupuesto","alert-warning")
    return redirect(url_for("consultas.lista_gestiones", criterio = id_gestion))

@consultas_bp.route("/consultas/caratula/")
@login_required
@not_initial_status
def caratula():
    id_gestion = request.args.get('id_gestion','')

    gestion = Gestiones.get_by_id(id_gestion)
    return render_template("consultas/caratula.html", gestion = gestion)
    
@consultas_bp.route("/consultas/bitacora/")
@login_required
@not_initial_status
def bitacora():
    id_gestion = request.args.get('id_gestion','')
    gestion = Gestiones.get_by_id(id_gestion)
    bitacora_completa = Observaciones.get_all_by_id_gestion(id_gestion)

    return render_template("consultas/bitacora.html", gestion = gestion, bitacora_completa=bitacora_completa)
    
@consultas_bp.route("/consultas/tareaspendientes/", methods = ['GET', 'POST'])
@login_required
@not_initial_status
def tareas_pendientes():
    id_gestion = request.args.get('id_gestion','')
    page = int(request.args.get('page', 1))
    per_page = current_app.config['ITEMS_PER_PAGE']
    
    if id_gestion:
        tareas_pendientes_por_gestion = GestionesDeTareas.get_gestiones_tareas_pendientes__por_gestiones_all_paginated(id_gestion, page, per_page)
    else:
        tareas_pendientes_por_gestion = GestionesDeTareas.get_gestiones_tareas_pendientes_all_paginated(page, per_page)
    
    return render_template("consultas/tareas_pendientes.html", tareas_pendientes_por_gestion = tareas_pendientes_por_gestion )

app/consultas/templates/consultas/bitacora.html
{% extends "base_template.html" %}

{% block title %}
    Ordeplos | Bitacora
{% endblock %}

{% block content %}

<div class="row">
    <div class="offset-md-2 col-md-8">
        <h3>Cliente: {{ gestion.personas.descripcion_nombre }} </h3>
        <h3>Número de gestión: {{ gestion.id }} </h3>
        <h3>Titular: {{ gestion.titular }} </h3> 
    </div>
    <div class="offset-md-2 col-md-8">
        {% for paso in bitacora_completa %}
            {% if paso.id_cobro and paso.id_importe_cobro %}
                <div class="card ml-5"><span class="border border-danger">        
                    <div class="card-body ">
                        <h6 class="card-title">Bitacora de cobro - {{paso.usuario_alta}} - {{paso.created.strftime('%d-%m-%Y')}}</h6>
                        {{ paso.observacion }}
                    </div>
            {% elif paso.id_cobro %}
                <div class="card ml-4"><span class="border border-warning">
                    <div class="card-body">
                        <h6 class="card-title">Bitacora de presupuesto - {{paso.usuario_alta}} - {{paso.created.strftime('%d-%m-%Y')}}</h6>
                        {{ paso.observacion }}
                    </div>
            {% elif paso.id_gestion_de_tarea %}
                <div class="card ml-3"><span class="border border-success">
                    <div class="card-body">
                        <h6 class="card-title">Bitacora de tarea - {{paso.usuario_alta}} - {{paso.created.strftime('%d-%m-%Y')}} - {{paso.gestionesdetareas.tareas.descripcion}}</h6>
                        {{ paso.observacion }}
                    </div>
            {% else %}
                <div class="card"><span class="border border-info">
                    <div class="card-body">
                        <h6 class="card-title">Bitacora de gestión - {{paso.usuario_alta}} - {{paso.created.strftime('%d-%m-%Y')}}</h6>
                        {{ paso.observacion }}
                    </div>
            {% endif %}
                </span>  
                </div>
        {% endfor %}

    </div>
</div> 
<a href="{{ url_for('gestiones.nuevo_paso', id_gestion = gestion.id) }}" >
    <button class="btn btn-primary">Nuevo Paso</button>
</a>

{% endblock %}

app/consultas/templates/consultas/caratula.html
{% extends "base_template.html" %}

{% block title %}
    Ordeplos | Caratula
{% endblock %}

{% block content %}
<div class="col-12">  
    <div id="zona_print">
      <div class="container">
      <div class="row">
        <div class="col-md-8">
          <h1>Dra. Patricia Sara Díaz </h1>
          <p>La plata</p>
          <p>Buenos Aires</p>
        
        </div>
        <div class="col-md-4">
          <div id="contenedorQR" >
            <p style="display: none;" >{{ url_for("gestiones.modificacion_gestiones", id_gestion = gestion.id, _external=True) }} </p>
          </div>
        </div>
      </div>
    
      <hr>
      <div class="col text-center">
        <h1>Cliente: {{ gestion.personas.descripcion_nombre }}</h1>
        <h2>N° de gestion: <strong>{{ gestion.id }}</strong> </h2>
      </div>
      <hr>
    
      <div class="row mt-3 col text-center">
        <div class="col-4">
          <h5>Tipo de gestion: </h5>
          <p>
            {{ gestion.tipos_gestiones.descripcion }} 
          </p>
        </div>
        <div class="col-4">
          
          <h5>Fecha: {{ gestion.created.strftime('%d-%m-%Y') }}</h5>
          <h5>Fecha cita: {{ gestion.fecha_cita.strftime('%d-%m-%Y') }}</h5>
        </div>
        <div class="col-4">
          <h5>Origen: <strong>{{ gestion.origen }}</strong></h5>
                 
        </div>
      </div>
      <hr>
      
    </div>
      
    </div>
  <a href="javascript:imprSelec('zona_print','Carátula')" >
    <button class="btn btn-primary">Imprimir</button>
  </a>  
</div>



{% endblock %}

app/consultas/templates/consultas/cobro.html
{% extends "base_template.html" %}
{% from "_render_elements.html" import render_input %}

{% block title %}
    Ordeplos | Cobro
{% endblock %}

{% block content %}



<div class="row mb-3">
	<div class="col-md-12 d-flex justify-content-between align-items-center">
		<h5 class="mb-0">Presupuesto de cobro</h5>
		<span class="badge badge-secondary">Gestión: {{ cobro_individual.id }}</span>
	</div>
</div>
<div class="row mb-3">
	<div class="col-md-4">
		<p class="mb-1 text-muted">Cliente</p>
		<p class="mb-0">{{ cobro_individual.personas.descripcion_nombre }}</p>
	</div>
	<div class="col-md-4">
		<p class="mb-1 text-muted">Gestion</p>
		<p class="mb-0">{{ cobro_individual.id }}</p>
	</div>
    <div class="col-md-4">
		<p class="mb-1 text-muted">Número de presupuesto</p>
		<a class="nav-link" href="{{ url_for('gestiones.modifica_cobros_cabecera', id_gestion = cobro_individual.id) }}">
		<p class="mb-0">{{ cobro_individual.cobro.id }}</p> 
		</a>
	</div>
</div>
<hr>
<div class="row mb-3">
	<div class="col-md-6">
		<p class="mb-1 text-muted">Moneda</p>
		<p class="mb-0">{{ cobro_individual.cobro.moneda }}</p>
	</div>
	<div class="col-md-6">
		<p class="mb-1 text-muted">Detalle</p>
		<p class="mb-0">Importe total: {{ cobro_individual.cobro.importe_total }}</p>
        {% if cobro_individual.cobro.importe_cobrado %}
			<p class="mb-0">Importe cobrado: {{ cobro_individual.cobro.importe_cobrado }}</p>
		{% else %}
			<p class="mb-0">Importe cobrado: 0 </p>
		{% endif %}
		<p class="mb-0">Debe: {{ cobro_individual.cobro.importe_total|float - cobro_individual.cobro.importe_cobrado|float }}</p>
	</div>
    
</div>
<a href=" {{ url_for('gestiones.alta_importe_cobro', id_gestion = cobro_individual.id) }} ">
    <button class="btn btn-light my-2 my-sm-0" type="submit">Cargar cobro</button>
</a> 
<hr>
<div class="row mt-4">
	{% if cobro_individual %}
	<div class="offset-md-1 col-md-9">
		<table class="table table-striped">
			<thead>
				<tr>
					<th scope="col">FECHA DE COBRO</th>
					<th scope="col">MEDIO DE COBRO</th>
					<th scope="col">MONEDA</th>
					<th scope="col">TIPO DE CAMBIO</th>
					<th scope="col">IMPORTE</th>
					<th scope="col">ACCION</th>
				</tr>
			</thead>

			<tbody>
				{% for cobro in cobro_individual.cobro.importes_cobros %}  
					<tr>
						<th scope="row">{{ cobro.fecha_cobro.strftime('%d-%m-%y') }}</th>
						<th scope="row">{{ cobro.medio_cobro }}</th>
						<th scope="row">{{ cobro.moneda }}</th>
						<th scope="row">{{ cobro.tipo_cambio }}</th>
						<th scope="row">{{ cobro.importe }}</th>
						<td>
							<div class="dropdown">
								<button class="btn btn-sm btn-secondary dropdown-toggle" data-bs-toggle="dropdown">
									Acción
							</button>
							<div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
								<li><a class="dropdown-item"  href="{{ url_for('gestiones.modificacion_importe_cobro', id_cobro_individual = cobro.id) }}">Modificar Cobro</a></li>
								<a class="dropdown-item"  href="#">Eliminar Cobro</a>
							</div>
						</td>
					</tr>
				{% endfor %}
			</tbody>
		</table>
	</div>	
	{% endif %}
</div>

{% endblock %}

app/consultas/templates/consultas/consulta_personas.html
{% extends "base_template.html" %}
{% from "_render_elements.html" import render_input %}

{% block title %}
    Ordeplos | Consulta de personas
{% endblock %}

{% block content %}
<div class="row">
	<div class="offset-md-3 col-md-6">
		<h1>Consulta de personas</h1>

		<form action="" method="post" enctype="multipart/form-data" novalidate>	
            {{ form.hidden_tag() }}
			{{ render_input(form.buscar,'', id= "buscar" , class="form-control", placeholder="Ingrese nombre/razón social o CUIT" ) }}
			<button type="submmit" class="btn btn-primary" >Buscar</button>
		</form>
	</div>
</div>
{% if lista_de_personas.items %}
<table class="table table-striped">
    <thead>
        <tr>
            <th scope="col">ID</th>
            <th scope="col">NOMBRE</th>
            <th scope="col">CUIT</th>
            <th scope="col">CORREO ELECTRONICO</th>
            <th scope="col">TIPO DE PERSONA</th>
            <th scope="col">ACCION</th> 
        </tr>
    </thead>
    
    <tbody>
        {% for persona in lista_de_personas.items %}
            <tr>
                <th scope="row">{{ persona.id }}</th>
                <td> {{ persona.descripcion_nombre }}</td>
                <td> {{ persona.cuit  }} </td>
                <td> {{ persona.correo_electronico }}</td>
                <td> {{ persona.tipo_persona }}</td>
                <td>
                    <div class="dropdown">
                        <button class="btn btn-sm btn-secondary dropdown-toggle" data-bs-toggle="dropdown">
                            Acción
                    </button>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item"  href="{{ url_for('admin.actualizacion_persona', id_persona = persona.id ) }}">Modificar</a></li>
                        <a class="dropdown-item"  href="#">Seleccionar</a>
                    </ul>
                </td>
            </tr>
        {% endfor %}
    </tbody>
</table>

<nav aria-label="Page navigation example">
	<ul class="pagination justify-content-center">
            <!-- <li class="page-item disabled">
                <a class="page-link" href="#">Anterior</a>
            </li> -->
        {%- for page in lista_de_personas.iter_pages() %}
			{% if page %}

				{% if page != lista_de_personas.page %}
					<li class="page-item"><a class="page-link" href="{{ url_for('consultas.consulta_personas', criterio= criterio, page=page) }}">{{ page }}</a>
				{% else %}
					<li class="page-item active">
						<span class="page-link">
							{{ page }}
							<span class="sr-only">(current)</span>
						</span>
					</li>
                {% endif %}
			{% endif %}
		{%- endfor %}
        <!-- <li class="page-item">
            <a class="page-link" href="#">Siguiente</a>
        </li> -->
	</ul>
</nav>


{% elif lista_de_personas %}

<table class="table table-striped">
    <thead>
        <tr>
            <th scope="col">ID</th>
            <th scope="col">NOMBRE</th>
            <th scope="col">CUIT</th>
            <th scope="col">CORREO ELECTRONICO</th>
            <th scope="col">TIPO DE PERSONA</th>
            <th scope="col">ACCION</th>
            
        </tr>
    </thead>
    
    <tbody>
        <tr>
            <th scope="row">{{ lista_de_personas.id }}</th>
            <td> {{ lista_de_personas.descripcion_nombre }}</td>
            <td> {{ lista_de_personas.cuit  }} </td>
            <td> {{ lista_de_personas.correo_electronico }}</td>
            <td> {{ lista_de_personas.tipo_persona }}</td>
            <td>
                <div class="dropdown">
                    <button class="btn btn-sm btn-secondary dropdown-toggle" data-bs-toggle="dropdown">
                        Acción
                </button>
                <ul class="dropdown-menu">
                    <li><a class="dropdown-item"  href="{{ url_for('admin.actualizacion_persona', id_persona = lista_de_personas.id ) }}">Modificar</a></li>
                    <a class="dropdown-item"  href="#">Seleccionar</a>
                </ul>
            </td>
        </tr>
    </tbody>
</table>

{% endif %}

{% endblock %}

app/consultas/templates/consultas/lista_gestiones.html
{% extends "base_template.html" %}
{% from "_render_elements.html" import render_input %}

{% block title %}
    Ordeplos | Gestiones
{% endblock %}

{% block content %}
<div class="row">
	<div class="offset-md-3 col-md-6">
		<h1>Consulta de Gestiones</h1>
            <form action="" method="post" enctype="multipart/form-data" novalidate>	
                {{ form.hidden_tag() }}
                {{ render_input(form.buscar,'', id= "buscar" , class="form-control", placeholder="Ingrese nombre/razón social o número de gestión" ) }}
                <button type="submmit" class="btn btn-primary" >Buscar</button>
            </form>
    </div>
</div>
{% if gestiones.items %}
<table class="table table-striped">
    <thead>
        <tr>
            <th scope="col">ID</th>
            <th scope="col">CLIENTE</th>
            <th scope="col">ORIGEN</th>
            <th scope="col">TIPO DE GESTION</th>
            <th scope="col">ACCION</th> 
        </tr>
    </thead>
    
    <tbody>
        {% for gestion in gestiones.items %}
            <tr>
                <th scope="row">{{ gestion.id }}</th>
                <td> {{ gestion.personas.descripcion_nombre }}</td>
                <td> {{ gestion.origen }} </td>
                <td> {{ gestion.tipos_gestiones.descripcion }}</td>
                <td>
                    <div class="dropdown">
                        <button class="btn btn-sm btn-secondary dropdown-toggle" data-bs-toggle="dropdown">
                            Acción
                        </button>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item"  href="{{ url_for('gestiones.modificacion_gestiones', id_gestion = gestion.id) }}">Modificar gestión</a></li>
                            <li><a class="dropdown-item"  href="{{ url_for('gestiones.alta_cobros_cabecera', id_gestion = gestion.id) }}">Crear presupuesto cobro</a></li>
                            <li><a class="dropdown-item"  href="{{ url_for('gestiones.nuevo_documento', id_gestion = gestion.id) }}">Agregar un documento</a></li>
                            <li><a class="dropdown-item"  href="{{ url_for('gestiones.gestiones_tareas', id_gestion = gestion.id) }}">Tareas</a></li>
                            <li><a class="dropdown-item"  href="{{ url_for('consultas.tareas_pendientes', id_gestion = gestion.id) }}">Tareas pendientes</a></li>
                            <li><a class="dropdown-item"  href="{{ url_for('consultas.cobro', id_gestion = gestion.id) }}">Ver presupuesto cobro</a></li>
                            <li><a class="dropdown-item"  href="{{ url_for('consultas.caratula', id_gestion = gestion.id)}} ">Carátula</a></li>
                            <li><a class="dropdown-item"  href="{{ url_for('consultas.bitacora', id_gestion = gestion.id) }}">Bitácora</a></li>
                    </div>
                </td>
            </tr>
        {% endfor %}
    </tbody>
</table>
<!-- uso un block para transformar esta vista a un template par poder distintos parametros en el navegador -->

{% block navpag %}{% endblock %}

{% elif gestiones %}

<table class="table table-striped">
    <thead>
        <tr>
            <th scope="col">ID</th>
            <th scope="col">CLIENTE</th>
            <th scope="col">ORIGEN</th>
            <th scope="col">TIPO DE GESTION</th>
            <th scope="col">ACCION</th>  
        </tr>
    </thead>
    
    <tbody>
        <tr>
            <th scope="row">{{ gestiones.id }}</th>
            <td> {{ gestiones.personas.descripcion_nombre }}</td>
            <td> {{ gestiones.origen }} </td>
            <td> {{ gestiones.tipos_gestiones.descripcion }}</td>
            <td>
                <div class="dropdown">
                    <button class="btn btn-sm btn-secondary dropdown-toggle" data-bs-toggle="dropdown">
                        Acción
                    </button>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item"  href="{{ url_for('gestiones.modificacion_gestiones', id_gestion = gestiones.id) }}">Modificar gestión</a></li>
                        <li><a class="dropdown-item"  href="{{ url_for('gestiones.alta_cobros_cabecera', id_gestion = gestiones.id) }}">Crear presupuesto cobro</a></li>
                        <li><a class="dropdown-item"  href="{{ url_for('gestiones.nuevo_documento', id_gestion = gestiones.id) }}">Agregar un documento</a></li>
                        <li><a class="dropdown-item"  href="{{ url_for('gestiones.gestiones_tareas', id_gestion = gestiones.id) }}">Tareas</a></li>
                        <li><a class="dropdown-item"  href="{{ url_for('consultas.cobro', id_gestion = gestiones.id) }}">Ver presupuesto cobro</a></li>
                        <li><a class="dropdown-item"  href="{{ url_for('consultas.caratula', id_gestion = gestiones.id)}} ">Carátula</a></li>
                        <li><a class="dropdown-item"  href="{{ url_for('consultas.bitacora', id_gestion = gestiones.id)}} ">Bitácora</a></li>
                    </ul>
                </div>
            </td>
        </tr>
    </tbody>
</table>

{% endif %}

{% endblock %}

app/consultas/templates/consultas/lista_gestiones_all_her.html
{% extends "consultas/lista_gestiones.html" %}
<!-- heredo desde el template lista_gestiones.html para poder usar el navegador de paginas con distintos parametros  -->

{% block navpag %}
    <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-center">

            {%- for page in gestiones.iter_pages() %}
                {% if page %}
                    {% if page != gestiones.page %}
                        <li class="page-item"><a class="page-link" href="{{ url_for('consultas.lista_gestiones', page=page) }}">{{ page }}</a>
                    {% else %}
                        <li class="page-item active">
                            <span class="page-link">
                                {{ page }}
                                <span class="sr-only"></span>
                            </span>
                        </li>
                    {% endif %}
                {% endif %}
            {%- endfor %}
        </ul>
    </nav>
{% endblock %}

app/consultas/templates/consultas/lista_gestiones_criterio.html
{% extends "consultas/lista_gestiones.html" %}
<!-- heredo desde el template lista_gestiones.html para poder usar el navegador de paginas con distintos parametros  -->

{% block navpag %}
    <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-center">

            {%- for page in gestiones.iter_pages() %}
                {% if page %}
                    {% if page != gestiones.page %}
                        <li class="page-item"><a class="page-link" href="{{ url_for('consultas.lista_gestiones', criterio=criterio, page=page) }}">{{ page }}</a>
                    {% else %}
                        <li class="page-item active">
                            <span class="page-link">
                                {{ page }}
                                <span class="sr-only"></span>
                            </span>
                        </li>
                    {% endif %}
                {% endif %}
            {%- endfor %}
        </ul>
    </nav>
{% endblock %}

app/consultas/templates/consultas/lista_gestiones_cuit_her.html
{% extends "consultas/lista_gestiones.html" %}
<!-- heredo desde el template lista_gestiones.html para poder usar el navegador de paginas con distintos parametros  -->

{% block navpag %}
    <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-center">

            {%- for page in gestiones.iter_pages() %}
                {% if page %}
                    {% if page != gestiones.page %}
                        <li class="page-item"><a class="page-link" href="{{ url_for('consultas.lista_gestiones', cuit=cuit, page=page) }}">{{ page }}</a>
                    {% else %}
                        <li class="page-item active">
                            <span class="page-link">
                                {{ page }}
                                <span class="sr-only"></span>
                            </span>
                        </li>
                    {% endif %}
                {% endif %}
            {%- endfor %}
        </ul>
    </nav>
{% endblock %}

app/consultas/templates/consultas/tareas_pendientes.html
{% extends "base_template.html" %}

{% block title %}
    Groma | Tareas Pendientes
{% endblock %}

{% block content %}

{% if tareas_pendientes_por_gestion.items %}
<table class="table table-striped">
    <thead>
        <tr>
            <th scope="col">TAREA</th>
            <th scope="col">CLIENTE</th>
            <th scope="col">TITULAR</th>
            <th scope="col">UBICACION</th>
            <th scope="col">TIPO DE GESTION</th>
            <th scope="col">FECHA INICIO</th>
            <th scope="col">ACCION</th> 
        </tr>
    </thead>
    
    <tbody>
        {% for tarea_pendiente in tareas_pendientes_por_gestion.items %}
            <tr>
                <th scope="row">{{ tarea_pendiente.tareas.descripcion }}</th>
                <td> {{ tarea_pendiente.gestiones.personas.descripcion_nombre }}</td>
                <td> {{ tarea_pendiente.gestiones.titular }} </td>
                <td> {{ tarea_pendiente.gestiones.ubicacion_gestion }}</td>
                <td> {{ tarea_pendiente.gestiones.tipos_gestiones.descripcion }}</td>
                <td> {{ tarea_pendiente.fecha_inicio }}</td>
                <td>
                    <div class="dropdown">
                        <button class="btn btn-sm btn-secondary dropdown-toggle" data-bs-toggle="dropdown">
                            Acción
                    </button>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item"  href="{{ url_for('gestiones.modificacion_gestiones', id_gestion = tarea_pendiente.gestiones.id) }}">Modificar gestión</a></li>
                        <li><a class="dropdown-item"  href="{{ url_for('gestiones.detalle_gdt', id_gestion_de_tarea = tarea_pendiente.id) }}">Modificar Tarea</a></li>
                        <li> <a class="dropdown-item"  href="{{ url_for('gestiones.gestiones_tareas', id_gestion = tarea_pendiente.gestiones.id) }}">Tareas</a></li>
                        <li><a class="dropdown-item"  href="{{ url_for('consultas.caratula', id_gestion = tarea_pendiente.gestiones.id)}} ">Carátula</a></li>
                        <li><a class="dropdown-item"  href="{{ url_for('consultas.bitacora', id_gestion = tarea_pendiente.gestiones.id) }}">Bitácora</a></li>
                    </ul>
                </td>
            </tr>
        {% endfor %}
    </tbody>
</table>

<nav aria-label="Page navigation example">
	<ul class="pagination justify-content-center">

        {%- for page in tareas_pendientes_por_gestion.iter_pages() %}
			{% if page %}

				{% if page != tareas_pendientes_por_gestion.page %}
					<li class="page-item"><a class="page-link" href="{{ url_for('consultas.tareas_pendientes', page=page) }}">{{ page }}</a>
				{% else %}
					<li class="page-item active">
						<span class="page-link">
							{{ page }}
							<span class="sr-only">(current)</span>
						</span>
					</li>
                {% endif %}
			{% endif %}
		{%- endfor %}
	</ul>
</nav>


{% endif %}

{% endblock %}